### PR TITLE
libntfs-3g: add checking for update sequence count in ntfs_mft_record…

### PR DESCRIPTION
**Pull request by jaysim**
…_check()

Add checking routine for update sequence count(usa).
If MFT record size is 1K, then usa count is 9 generally.

Add some comments.

### CODE REVIEW

**Comment by namjaejeon** [comment]
I have checked related codes in ntfs. It was using NTFS_BLOCK_SIZE(512byte) instead of vol->sector_size.
We need to check how ->usa_count value is calculated on 4K native storage(HW 4K sector) later.
Anyway, I will apply it! Thanks!

```
        if (vol->mft_record_size >= NTFS_BLOCK_SIZE)
                m->usa_count = cpu_to_le16(vol->mft_record_size /
                                NTFS_BLOCK_SIZE + 1);
        else {
                m->usa_count = cpu_to_le16(1);
                ntfs_warning(vol->sb, "Sector size is bigger than mft record "
                                "size.  Setting usa_count to 1.  If chkdsk "
                                "reports this as corruption, please email "
                                "linux-ntfs-dev@lists.sourceforge.net stating "
                                "that you saw this message and that the "
                                "modified filesystem created was corrupt.  "
                                "Thank you.");
        }
```

**Comment by namjaejeon** [comment]
one more, When you create a patch, you need to check signedoff-by tag in the patch like this.
I have manually added it on your patch.
```
Author: JaeHoon Sim <jay.sim@lge.com>
Date:   Tue Oct 11 11:34:09 2022 +0900

    libntfs-3g: add checking for update sequence count in ntfs_mft_record_check()
    
    Add checking routine for update sequence count(usa).
    If MFT record size is 1K, then usa count is 9 generally.
    
    Add some comments.
    
    Signed-off-by: JaeHoon Sim <jay.sim@lge.com>
```

**Comment by namjaejeon** [comment]
Applied thanks!

**Comment by jaysim** [comment]
> one more, When you create a patch, you need to check signedoff-by tag in the patch like this. I have manually added it on your patch.
> 
> ```
> Author: JaeHoon Sim <jay.sim@lge.com>
> Date:   Tue Oct 11 11:34:09 2022 +0900
> 
>     libntfs-3g: add checking for update sequence count in ntfs_mft_record_check()
>     
>     Add checking routine for update sequence count(usa).
>     If MFT record size is 1K, then usa count is 9 generally.
>     
>     Add some comments.
>     
>     Signed-off-by: JaeHoon Sim <jay.sim@lge.com>
> ```

I ask for reverting this patch, because update sequence count check is already done in is_valid_record() which is calling from ntfs_mft_records_read(). sorry for that.

And ok, I'll add signed-off tag after this time.

**Comment by namjaejeon** [comment]
OK!

**Pull request closed without merging**
